#%RAML 1.0 NamedExample
value: |
  [ 

    {
      "orderNo": "1",
      "ItemId": 88,
      "ItemName":"Smart Slim Micro Stripe Shirt",
      "price" : "500",
      "quantity":1
    },
    {
      "orderNo": "2",
      "ItemId": 8,
      "ItemName":"Smart Slim Shirt",
      "price" : "400",
      "quantity":4
    },
    {
      "orderNo":"3",
      "ItemId": 18,
      "ItemName":"Smart Slim green Shirt",
      "price" : "600",
      "quantity":2
    }
  ]